//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ManageMe.Domain.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class Activity
    {
        public Activity()
        {
            this.LU_Activity_SupportingDoc = new HashSet<LU_Activity_SupportingDoc>();
            this.Issue = new HashSet<Issue>();
        }
    
        public int ActivityId { get; set; }
        public Nullable<int> ActivityTypeId { get; set; }
        public Nullable<System.DateTime> ActivityDate { get; set; }
        public Nullable<int> ActedBy { get; set; }
        public string Description { get; set; }
        public Nullable<decimal> Cost { get; set; }
        public Nullable<int> LaborHours { get; set; }
        public Nullable<int> Status { get; set; }
    
        public virtual ICollection<LU_Activity_SupportingDoc> LU_Activity_SupportingDoc { get; set; }
        public virtual ICollection<Issue> Issue { get; set; }
        public virtual LU_ObjectAttribute ActivityStatus { get; set; }
        public virtual LU_ObjectAttribute ActivityType { get; set; }
        public virtual Provider Provider { get; set; }
    }
}
