//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ManageMe.Domain.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class HomeInsurance
    {
        public int Id { get; set; }
        public Nullable<int> PropertyID { get; set; }
        public string PolicyNumber { get; set; }
        public Nullable<System.DateTime> EffectiveDate { get; set; }
        public Nullable<System.DateTime> ExpireDate { get; set; }
        public Nullable<decimal> AnnualPremium { get; set; }
        public Nullable<decimal> Deductible { get; set; }
        public Nullable<decimal> DwellingCoverage { get; set; }
        public Nullable<decimal> OtherStructureCoverage { get; set; }
        public Nullable<decimal> PersonalPropertyCoverage { get; set; }
        public Nullable<decimal> FamilyLiability { get; set; }
        public Nullable<decimal> MedicalPayment { get; set; }
        public Nullable<decimal> FireDeptCharge { get; set; }
        public Nullable<int> InsuranceAgentContactID { get; set; }
        public string Comments { get; set; }
        public Nullable<int> UtilityCompanyId { get; set; }
    
        public virtual Provider Provider { get; set; }
        public virtual RProperty RProperty { get; set; }
        public virtual UtilityCompany UtilityCompany { get; set; }
    }
}
