//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ManageMe.Domain.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class LU_Activity_SupportingDoc
    {
        public int ActivityDocId { get; set; }
        public int ActivityId { get; set; }
        public System.Guid SupportingDocId { get; set; }
        public Nullable<System.DateTime> ReceivedDate { get; set; }
        public string Vendor { get; set; }
        public Nullable<decimal> Amount { get; set; }
        public string Notes { get; set; }
        public string DocName { get; set; }
    
        public virtual Activity Activity { get; set; }
    }
}
