//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ManageMe.Domain.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class LU_DocType
    {
        public int IDocTypeId { get; set; }
        public string TypeName { get; set; }
        public int Ordinal { get; set; }
        public int ObjectId { get; set; }
    }
}
