//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ManageMe.Domain.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class LU_IssueReportMethod
    {
        public int IssueReportMethodId { get; set; }
        public string MethodName { get; set; }
        public Nullable<int> Ordinal { get; set; }
    }
}
