//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ManageMe.Domain.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class LU_Lender
    {
        public LU_Lender()
        {
            this.Mortgage = new HashSet<Mortgage>();
        }
    
        public int Id { get; set; }
        public string AddressLine1 { get; set; }
        public string AddressLine2 { get; set; }
        public string City { get; set; }
        public string State { get; set; }
        public string Phone { get; set; }
        public string WebAddress { get; set; }
        public string LenderName { get; set; }
        public string Fax { get; set; }
        public string Zip { get; set; }
    
        public virtual ICollection<Mortgage> Mortgage { get; set; }
    }
}
