//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ManageMe.Domain.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class LU_LeaseDoc
    {
        public int Id { get; set; }
        public int LeaseId { get; set; }
        public System.Guid DocStreamId { get; set; }
        public string Notes { get; set; }
        public int DocTypeId { get; set; }
        public string DocName { get; set; }
        public Nullable<int> StatusId { get; set; }
    
        public virtual Lease Lease { get; set; }
        public virtual LU_DocType LU_DocType { get; set; }
        public virtual LU_ObjectAttribute LU_ObjectAttribute { get; set; }
    }
}
