//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ManageMe.Domain.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class LU_Object
    {
        public LU_Object()
        {
            this.LU_ObjectAttribute = new HashSet<LU_ObjectAttribute>();
        }
    
        public int Id { get; set; }
        public string ObjectName { get; set; }
    
        public virtual ICollection<LU_ObjectAttribute> LU_ObjectAttribute { get; set; }
    }
}
