//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ManageMe.Domain.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class LU_ObjectAttribute
    {
        public LU_ObjectAttribute()
        {
            this.Activity = new HashSet<Activity>();
            this.Activity1 = new HashSet<Activity>();
            this.Issue = new HashSet<Issue>();
            this.LU_LeaseDoc = new HashSet<LU_LeaseDoc>();
            this.Provider = new HashSet<Provider>();
            this.Mortgage = new HashSet<Mortgage>();
            this.Mortgage1 = new HashSet<Mortgage>();
            this.UtilityCompany = new HashSet<UtilityCompany>();
        }
    
        public int Id { get; set; }
        public string Attribute { get; set; }
        public int ObjectAttributeTypeId { get; set; }
        public int ObjectId { get; set; }
        public Nullable<int> Ordinal { get; set; }
    
        public virtual ICollection<Activity> Activity { get; set; }
        public virtual ICollection<Activity> Activity1 { get; set; }
        public virtual ICollection<Issue> Issue { get; set; }
        public virtual ICollection<LU_LeaseDoc> LU_LeaseDoc { get; set; }
        public virtual LU_Object LU_Object { get; set; }
        public virtual LU_ObjectAttributeType LU_ObjectAttributeType { get; set; }
        public virtual ICollection<Provider> Provider { get; set; }
        public virtual ICollection<Mortgage> Mortgage { get; set; }
        public virtual ICollection<Mortgage> Mortgage1 { get; set; }
        public virtual ICollection<UtilityCompany> UtilityCompany { get; set; }
    }
}
