//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ManageMe.Domain.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class LU_ServiceAgent
    {
        public LU_ServiceAgent()
        {
            this.Mortgage = new HashSet<Mortgage>();
        }
    
        public int Id { get; set; }
        public Nullable<int> PropertyServiceId { get; set; }
        public Nullable<int> AgentId { get; set; }
        public Nullable<int> objectId { get; set; }
    
        public virtual Provider Provider { get; set; }
        public virtual ICollection<Mortgage> Mortgage { get; set; }
    }
}
