//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ManageMe.Domain.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class Mortgage
    {
        public int Id { get; set; }
        public Nullable<System.DateTime> StartDate { get; set; }
        public Nullable<int> TermDuration { get; set; }
        public Nullable<decimal> Rate { get; set; }
        public Nullable<decimal> MonthlyPayment { get; set; }
        public Nullable<int> LenderId { get; set; }
        public Nullable<int> MortgageStatusId { get; set; }
        public Nullable<int> MortgageTypeId { get; set; }
        public int RPropertyId { get; set; }
        public string Notes { get; set; }
        public Nullable<int> PaymentDate { get; set; }
        public string LoanId { get; set; }
        public string OMB { get; set; }
        public string RecipientTaxId { get; set; }
        public Nullable<int> EndingBalance { get; set; }
        public Nullable<int> ServiceAgentId { get; set; }
    
        public virtual LU_Lender LU_Lender { get; set; }
        public virtual LU_ObjectAttribute MortgageStatus { get; set; }
        public virtual LU_ObjectAttribute MortgageType { get; set; }
        public virtual RProperty RProperty { get; set; }
        public virtual LU_ServiceAgent LU_ServiceAgent { get; set; }
    }
}
