//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ManageMe.Domain.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class Renter
    {
        public Renter()
        {
            this.Issue = new HashSet<Issue>();
            this.RenterIdentityDocument = new HashSet<RenterIdentityDocument>();
            this.Lease = new HashSet<Lease>();
        }
    
        public int RenterId { get; set; }
        public string FirstName { get; set; }
        public string LastName { get; set; }
        public string MiddleName { get; set; }
        public string CellPhone { get; set; }
        public string HomePhone { get; set; }
        public string EmailAddress { get; set; }
        public string Comments { get; set; }
    
        public virtual ICollection<Issue> Issue { get; set; }
        public virtual ICollection<RenterIdentityDocument> RenterIdentityDocument { get; set; }
        public virtual ICollection<Lease> Lease { get; set; }
    }
}
