//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ManageMe.Domain.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class RenterIdentityDocument
    {
        public int DocNumber { get; set; }
        public string Issuer { get; set; }
        public System.DateTime IssueDate { get; set; }
        public System.DateTime ExpirationDate { get; set; }
        public int DocTypeId { get; set; }
        public int RenterId { get; set; }
        public Nullable<System.Guid> StreamFileId { get; set; }
    
        public virtual LU_DocType LU_DocType { get; set; }
        public virtual Renter Renter { get; set; }
    }
}
