//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ManageMe.Domain.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class REPropertyTax
    {
        public int Id { get; set; }
        public Nullable<int> PropertyID { get; set; }
        public string CountyName { get; set; }
        public Nullable<decimal> TotalAssessedValue { get; set; }
        public Nullable<decimal> BuildingAssessedValue { get; set; }
        public Nullable<decimal> LandAssessedValue { get; set; }
        public Nullable<int> AssessmentYear { get; set; }
        public Nullable<decimal> AnnualTaxAmount { get; set; }
        public Nullable<decimal> FirstPaymentAmount { get; set; }
        public Nullable<System.DateTime> FirstPaymentPaidDate { get; set; }
        public Nullable<decimal> SecondPaymentAmount { get; set; }
        public Nullable<System.DateTime> SecondPaymentPaidDate { get; set; }
        public string Comments { get; set; }
    
        public virtual RProperty RProperty { get; set; }
    }
}
