//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ManageMe.Domain.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class RProperty
    {
        public RProperty()
        {
            this.Issue = new HashSet<Issue>();
            this.Lease = new HashSet<Lease>();
            this.HOA = new HashSet<HOA>();
            this.HomeInsurance = new HashSet<HomeInsurance>();
            this.REPropertyTax = new HashSet<REPropertyTax>();
            this.Mortgage = new HashSet<Mortgage>();
        }
    
        public int RPropertyId { get; set; }
        public string PropName { get; set; }
        public string AddressLine1 { get; set; }
        public string AddressLine2 { get; set; }
        public string City { get; set; }
        public string State { get; set; }
        public string Zip { get; set; }
        public string MailBoxNum { get; set; }
        public string ParkingNum { get; set; }
        public string TrashPickupTime { get; set; }
    
        public virtual ICollection<Issue> Issue { get; set; }
        public virtual ICollection<Lease> Lease { get; set; }
        public virtual ICollection<HOA> HOA { get; set; }
        public virtual ICollection<HomeInsurance> HomeInsurance { get; set; }
        public virtual ICollection<REPropertyTax> REPropertyTax { get; set; }
        public virtual ICollection<Mortgage> Mortgage { get; set; }
    }
}
