//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ManageMe.Domain.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class UtilityCompany
    {
        public UtilityCompany()
        {
            this.HomeInsurance = new HashSet<HomeInsurance>();
        }
    
        public int Id { get; set; }
        public int UtilityCoTypeID { get; set; }
        public string UtilityCoName { get; set; }
        public string UtilityCoPhone { get; set; }
        public string UtilityCoWebsite { get; set; }
        public string UtilityCoLoginAccount { get; set; }
        public string UtilityCoLoginPwdHint { get; set; }
        public string Comments { get; set; }
        public string UtilityCoFax { get; set; }
        public Nullable<int> UtilityCoAddressId { get; set; }
    
        public virtual LU_ObjectAttribute LU_ObjectAttribute { get; set; }
        public virtual LU_Address LU_Address { get; set; }
        public virtual ICollection<HomeInsurance> HomeInsurance { get; set; }
    }
}
